#!/usr/bin/env python3
"""
qc_sample_pairs.py — Spot-check synthetic SFT pairs against the corpus chunks they came from.

Draws a random (category-stratified) sample of N pairs from generated training data, looks up
each pair's source chunk in the corpus by `source_chunk_id`, and writes:

  <out-dir>/qc_review.md     human-readable: passage | user turn | assistant turn | rating checklist
  <out-dir>/qc_review.jsonl  one record per pair, with automatic checks, optional GPT-4o judgement,
                             and blank fields (grounded/accurate/category_fit/naturalness/notes)
                             for hand-filling

Automatic checks (free, no API): output word count vs the 150-300 target, meta-instruction leakage,
and "entity grounding" = fraction of gene/protein-like tokens in the answer that also appear in the
passage (a low value flags answers written from the teacher's memory rather than the paper — not
necessarily wrong, but the ones to read first).

--judge adds a GPT-4o pass (needs OPENAI_API_KEY): claim-level support check of the answer against
the passage, plus question-grounding and category-fit scores. Treat it as triage, not ground truth —
the judge only sees the passage, so "unsupported" means "not in this chunk", not "false".

Usage:
    python qc_sample_pairs.py \
        --data   '/uss/skavlak/version_3/training_data_shard_*.jsonl' \
        --corpus /uss/skavlak/version_3/corpus_v3_train.jsonl \
        --n 60 --seed 1 --out-dir qc_out [--judge]

Re-run with a different --seed for a fresh draw. Accepts JSONL or concatenated pretty-printed JSON.
"""

from __future__ import annotations

import argparse
import glob
import json
import math
import os
import random
import re
from collections import defaultdict
from pathlib import Path

META_PATTERNS = re.compile(
    r"step \d+:|instruction-response pair|training example|^\s*here (is|are) (the|your|an?) |"
    r"^\s*(Instruction|Input|Output):|\bas an ai\b|seed example",
    re.IGNORECASE | re.MULTILINE,
)
# Rv numbers, camel-case gene names (katG, rpoB, WhiB4), and acronyms/protein names (ESX-1, PknB)
ENTITY_RE = re.compile(r"\bRv\d{4}c?\b|\b[a-z]{3}[A-Z]\d?\b|\b[A-Z][a-z]{2}[A-Z0-9]\w*\b|\b[A-Z]{2,}[A-Za-z0-9-]*\b")
STOP_ENTITIES = {"TB", "MTB", "DNA", "RNA", "PCR", "HIV", "WHO", "AND", "THE", "FOR", "USA", "ATP"}

JUDGE_PROMPT = """\
You are auditing a synthetic training example for a tuberculosis research-assistant LLM.
The example was generated by a teacher model from the SOURCE PASSAGE below, in the category "{category}".

SOURCE PASSAGE:
{passage}

USER TURN (instruction + researcher question):
{user}

ASSISTANT TURN:
{assistant}

Tasks:
1. question_grounded: is the researcher's question clearly inspired by / answerable in the context of
   the passage's topic? (1 = unrelated, 5 = directly about its content)
2. claims: list the specific factual claims in the assistant turn (max 8, most important first).
   For each give a verdict:
     "supported"    — stated or directly implied by the passage
     "unsupported"  — not in the passage (may still be true general knowledge)
     "contradicted" — conflicts with the passage
3. category_fit: does the example do what a "{category}" example should? (1-5)
4. issues: short list of any problems (invented numbers, wrong organism, leaked meta-text, premise
   not in passage, etc.). Empty list if none.

Respond with JSON only:
{{"question_grounded": 1-5, "claims": [{{"claim": "...", "verdict": "supported|unsupported|contradicted"}}],
 "category_fit": 1-5, "issues": ["..."]}}"""


def read_records(path: str):
    """Yield dicts from JSONL or concatenated (possibly pretty-printed) JSON."""
    text = Path(path).read_text(encoding="utf-8")
    dec, i = json.JSONDecoder(), 0
    while i < len(text):
        while i < len(text) and text[i].isspace():
            i += 1
        if i >= len(text):
            break
        obj, i = dec.raw_decode(text, i)
        yield obj


def sample_pairs(paths: list[str], n: int, seed: int, stratify: bool) -> list[dict]:
    rng = random.Random(seed)
    by_cat = defaultdict(list)
    total = 0
    for p in paths:
        for rec in read_records(p):
            if "messages" not in rec or "source_chunk_id" not in rec:
                continue
            by_cat[rec.get("category", "unknown")].append(rec)
            total += 1
    print(f"Loaded {total} pairs across {len(by_cat)} categories from {len(paths)} file(s)")
    if not stratify:
        flat = [r for rs in by_cat.values() for r in rs]
        return rng.sample(flat, min(n, len(flat)))
    per_cat = math.ceil(n / len(by_cat))
    out = []
    for cat in sorted(by_cat):
        out += rng.sample(by_cat[cat], min(per_cat, len(by_cat[cat])))
    rng.shuffle(out)
    return out[:n]


def load_chunks(corpus_path: str, wanted: set[str]) -> dict[str, dict]:
    found, dupes = {}, 0
    with open(corpus_path, encoding="utf-8") as f:
        for line in f:
            obj = json.loads(line)
            cid = obj.get("id")
            if cid in wanted:
                if cid in found:
                    dupes += 1  # PDF-path ids ("chunk_0001") are per-document, not globally unique
                found[cid] = obj
    if dupes:
        print(f"WARNING: {dupes} source_chunk_ids matched >1 corpus chunk — passage may be the wrong one")
    return found


def passage_body(chunk: dict) -> str:
    raw = chunk.get("text", "")
    return raw[raw.index("\n\n") + 2:] if "\n\n" in raw else raw


def auto_checks(assistant: str, passage: str) -> dict:
    ents = {e for e in ENTITY_RE.findall(assistant) if e.upper() not in STOP_ENTITIES}
    in_passage = {e for e in ents if e.lower() in passage.lower()}
    return {
        "words": len(assistant.split()),
        "meta_leak": bool(META_PATTERNS.search(assistant)),
        "n_entities": len(ents),
        "entity_grounding": round(len(in_passage) / len(ents), 2) if ents else None,
        "ungrounded_entities": sorted(ents - in_passage)[:12],
    }


def judge(client, model: str, rec: dict, passage: str) -> dict | None:
    prompt = JUDGE_PROMPT.format(
        category=rec["category"], passage=passage[:3000],
        user=rec["user"], assistant=rec["assistant"],
    )
    try:
        resp = client.chat.completions.create(
            model=model, temperature=0.0, max_tokens=900,
            response_format={"type": "json_object"},
            messages=[{"role": "user", "content": prompt}],
        )
        return json.loads(resp.choices[0].message.content)
    except Exception as e:
        print(f"  [judge error] {rec['source_chunk_id']}: {e}")
        return None


def render_md(records: list[dict]) -> str:
    out = ["# Synthetic data QC review\n",
           "Rate each pair: **grounded** (answer consistent with passage), **accurate** (true per your "
           "TB knowledge), **category_fit**, **naturalness** (1-5), and add notes. "
           "Fill these in `qc_review.jsonl` or just keep tallies here.\n"]
    for i, r in enumerate(records, 1):
        a = r["auto"]
        out.append(f"\n---\n\n## {i}. `{r['category']}` — {r['document_name']} / {r['section']}\n")
        out.append(f"chunk id: `{r['source_chunk_id']}`  |  words: {a['words']}  |  "
                   f"entity grounding: {a['entity_grounding']}  |  meta-leak: {a['meta_leak']}\n")
        if a["ungrounded_entities"]:
            out.append(f"Entities in answer not in passage: {', '.join(a['ungrounded_entities'])}\n")
        out.append("\n### Source passage\n\n" + "\n".join("> " + l for l in r["passage"].splitlines()) + "\n")
        out.append("\n### User turn\n\n" + r["user"] + "\n")
        out.append("\n### Assistant turn\n\n" + r["assistant"] + "\n")
        j = r.get("judge")
        if j:
            out.append(f"\n### GPT-4o triage (question_grounded={j.get('question_grounded')}, "
                       f"category_fit={j.get('category_fit')})\n")
            for c in j.get("claims", []):
                mark = {"supported": "✅", "unsupported": "❓", "contradicted": "❌"}.get(c.get("verdict"), "?")
                out.append(f"- {mark} {c.get('claim')}")
            if j.get("issues"):
                out.append("\nIssues: " + "; ".join(j["issues"]))
            out.append("")
        out.append("\n**Your rating:** grounded [ ]  accurate [ ]  category_fit [ ]  naturalness [ /5]  notes: \n")
    return "\n".join(out)


def summarize(records: list[dict]) -> None:
    n = len(records)
    g = [r["auto"]["entity_grounding"] for r in records if r["auto"]["entity_grounding"] is not None]
    print(f"\n=== Summary over {n} pairs ===")
    print(f"meta-leak flagged : {sum(r['auto']['meta_leak'] for r in records)}")
    print(f"outside 150-300 w : {sum(not 150 <= r['auto']['words'] <= 300 for r in records)}")
    if g:
        print(f"mean entity grounding: {sum(g)/len(g):.2f}  (<0.5 for {sum(x < 0.5 for x in g)})")
    js = [r["judge"] for r in records if r.get("judge")]
    if js:
        verdicts = [c.get("verdict") for j in js for c in j.get("claims", [])]
        for v in ("supported", "unsupported", "contradicted"):
            print(f"judge claims {v:13s}: {verdicts.count(v)}/{len(verdicts)}")
        print(f"pairs with a contradicted claim: {sum(any(c.get('verdict') == 'contradicted' for c in j.get('claims', [])) for j in js)}/{len(js)}")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data", required=True, nargs="+", help="file path(s) or glob(s) of generated pairs")
    ap.add_argument("--corpus", required=True)
    ap.add_argument("--n", type=int, default=50)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--no-stratify", action="store_true", help="uniform random instead of per-category")
    ap.add_argument("--out-dir", default="qc_out")
    ap.add_argument("--judge", action="store_true", help="add GPT-4o claim-level triage (needs OPENAI_API_KEY)")
    ap.add_argument("--judge-model", default="gpt-4o")
    args = ap.parse_args()

    paths = sorted(p for pat in args.data for p in glob.glob(pat))
    if not paths:
        raise SystemExit(f"No files match {args.data}")

    sample = sample_pairs(paths, args.n, args.seed, not args.no_stratify)
    chunks = load_chunks(args.corpus, {r["source_chunk_id"] for r in sample})
    missing = [r["source_chunk_id"] for r in sample if r["source_chunk_id"] not in chunks]
    if missing:
        print(f"WARNING: {len(missing)} source chunks not found in corpus (dropped): {missing[:5]}")

    client = None
    if args.judge:
        from openai import OpenAI
        client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

    records = []
    for i, r in enumerate(sample, 1):
        chunk = chunks.get(r["source_chunk_id"])
        if chunk is None:
            continue
        msgs = {m["role"]: m["content"] for m in r["messages"]}
        passage = passage_body(chunk)
        rec = {
            "source_chunk_id": r["source_chunk_id"],
            "category": r.get("category", "unknown"),
            "document_name": chunk.get("document_name", ""),
            "section": chunk.get("section_title", ""),
            "passage": passage,
            "user": msgs.get("user", ""),
            "assistant": msgs.get("assistant", ""),
            "auto": auto_checks(msgs.get("assistant", ""), passage),
            # blank human-rating fields
            "grounded": None, "accurate": None, "category_fit": None, "naturalness": None, "notes": "",
        }
        if client:
            rec["judge"] = judge(client, args.judge_model, rec, passage)
            if i % 10 == 0:
                print(f"  judged {i}/{len(sample)}")
        records.append(rec)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    with open(out_dir / "qc_review.jsonl", "w", encoding="utf-8") as f:
        for rec in records:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
    (out_dir / "qc_review.md").write_text(render_md(records), encoding="utf-8")
    print(f"Wrote {len(records)} pairs to {out_dir}/qc_review.md and qc_review.jsonl")
    summarize(records)


if __name__ == "__main__":
    main()
